import {
  FaApple,
  FaCarrot,
  FaCheese,
  FaCookieBite,
  FaGlassMartiniAlt,
  FaLemon,
  FaCashRegister,
  FaShoppingCart,
  FaBreadSlice,
  FaPepperHot,
  FaDrumstickBite,
  FaCookie,
  FaFish,
  FaIceCream,
  FaPizzaSlice,
  FaHamburger,
  FaHotdog,
  FaCandyCane,
  FaBlender,
  FaEgg,
  FaMugHot,
  FaBacon,
  FaUtensils,
  FaBeer,
  FaWineBottle,
  FaLeaf,
  FaCoffee,
  FaCocktail,
  FaConciergeBell,
  FaGift,
  FaTrophy,
  FaClipboardList,
  FaBalanceScale,
  FaWarehouse,
  FaPercentage,
  FaTruck,
  FaTruckLoading,
  FaTruckMoving,
  FaBox,
  FaAppleAlt,
  FaWineGlassAlt,
} from "react-icons/fa";
import {
  TbSoup,
  TbSausage,
  TbSoupFilled,
  TbSalad,
  TbCoffee,
  TbIceCream2,
  TbBottle,
  TbApple,
  TbCup,
  TbCake,
  TbMilk,
  TbBowlChopsticks,
} from "react-icons/tb";
import {
  GiChiliPepper,
  GiBananaBunch,
  GiAvocado,
  GiMeat,
  GiNoodles,
  GiCheeseWedge,
  GiSodaCan,
  GiSteak,
  GiBread,
  GiChickenLeg,
  GiStrawberry,
  GiPear,
  GiWatermelon,
  GiGrapes,
  GiHotMeal,
  GiMeatCleaver,
  GiCoffeeCup,
  GiBowlOfRice,
  GiSmokingPipe,
  GiBacon,
  GiBeerStein,
  GiBigEgg,
  GiBottleVapors,
  GiCabbage,
  GiCannedFish,
  GiChopsticks,
  GiCook,
  GiCroissant,
  GiCupcake,
  GiEggPod,
  GiFlour,
  GiFrenchFries,
  GiHoneyJar,
  GiHotSpices,
  GiMilkCarton,
  GiMushroom,
  GiPineapple,
  GiPizzaSlice,
  GiPotato,
  GiShrimp,
  GiTomato,
  GiCoconuts,
  GiClaymoreExplosive,
  GiSandwich,
} from "react-icons/gi";
import {
  MdFoodBank,
  MdFastfood,
  MdIcecream,
  MdLocalPizza,
  MdOutlineWineBar,
  MdRamenDining,
  MdOutlineSetMeal,
} from "react-icons/md";

import { SiCoffeescript } from "react-icons/si";
import { RiDrinksFill } from "react-icons/ri";
import { LuChefHat } from "react-icons/lu";
import { GiChickenOven } from "react-icons/gi";
import { GiManualJuicer } from "react-icons/gi";
import { MdChildCare } from "react-icons/md";
import { FaBottleWater } from "react-icons/fa6";
import { BiSolidDish } from "react-icons/bi";
import { SlEnergy } from "react-icons/sl";
import { GiCooler } from "react-icons/gi";
import { RiDrinks2Fill } from "react-icons/ri";
import { PiHamburgerFill } from "react-icons/pi";

export const iconOptions = [
  { title: "Utensils", value: <FaUtensils className="h-4 w-4" /> },
  { title: "Pizza", value: <FaPizzaSlice className="h-4 w-4" /> },
  { title: "Hamburger", value: <FaHamburger className="h-4 w-4" /> },
  { title: "Ice Cream", value: <FaIceCream className="h-4 w-4" /> },
  { title: "Coffee", value: <FaCoffee className="h-4 w-4" /> },
  { title: "Cocktail", value: <FaCocktail className="h-4 w-4" /> },
  { title: "Fish", value: <FaFish className="h-4 w-4" /> },
  { title: "Vegan", value: <FaLeaf className="h-4 w-4" /> },
  { title: "Wine", value: <FaWineBottle className="h-4 w-4" /> },
  { title: "Service", value: <FaConciergeBell className="h-4 w-4" /> },
  { title: "Fruit", value: <GiBananaBunch className="h-4 w-4" /> },
  { title: "Bread", value: <GiBread className="h-4 w-4" /> },
  { title: "Chicken", value: <GiChickenLeg className="h-4 w-4" /> },
  { title: "Spicy", value: <GiChiliPepper className="h-4 w-4" /> },
  { title: "Beer", value: <FaBeer className="h-4 w-4" /> },
  { title: "Cheese", value: <GiCheeseWedge className="h-4 w-4" /> },
  { title: "Noodles", value: <GiNoodles className="h-4 w-4" /> },
  { title: "Steak", value: <GiSteak className="h-4 w-4" /> },
  { title: "Soda", value: <GiSodaCan className="h-4 w-4" /> },
  { title: "Egg", value: <FaEgg className="h-4 w-4" /> },
  { title: "Avocado", value: <GiAvocado className="h-4 w-4" /> },
  { title: "Candy", value: <FaCandyCane className="h-4 w-4" /> },
  { title: "Milk", value: <TbMilk className="h-4 w-4" /> },
  { title: "Watermelon", value: <GiWatermelon className="h-4 w-4" /> },
  { title: "Pear", value: <GiPear className="h-4 w-4" /> },
  { title: "Strawberry", value: <GiStrawberry className="h-4 w-4" /> },
  { title: "Cookie", value: <FaCookie className="h-4 w-4" /> },
  { title: "Box", value: <FaBox className="h-4 w-4" /> },
  { title: "Delivery Truck", value: <FaTruck className="h-4 w-4" /> },
  { title: "Trophy", value: <FaTrophy className="h-4 w-4" /> },
  { title: "Order List", value: <FaClipboardList className="h-4 w-4" /> },
  { title: "Scale", value: <FaBalanceScale className="h-4 w-4" /> },
  { title: "Warehouse", value: <FaWarehouse className="h-4 w-4" /> },
  { title: "Discount", value: <FaPercentage className="h-4 w-4" /> },
  { title: "Loading Truck", value: <FaTruckLoading className="h-4 w-4" /> },
  { title: "Moving Truck", value: <FaTruckMoving className="h-4 w-4" /> },
  { title: "Soup", value: <TbSoupFilled className="h-4 w-4" /> },
  { title: "Gift", value: <FaGift className="h-4 w-4" /> },
  { title: "Hot Mug", value: <FaMugHot className="h-4 w-4" /> },
  { title: "Hot Dog", value: <FaHotdog className="h-4 w-4" /> },
  { title: "Bacon", value: <FaBacon className="h-4 w-4" /> },
  { title: "Cake", value: <TbCake className="h-4 w-4" /> },
  { title: "Meat", value: <GiMeat className="h-4 w-4" /> },
  { title: "Grapes", value: <GiGrapes className="h-4 w-4" /> },
  { title: "Hot Meal", value: <GiHotMeal className="h-4 w-4" /> },
  { title: "Meat Cleaver", value: <GiMeatCleaver className="h-4 w-4" /> },
  { title: "Coffee Cup", value: <SiCoffeescript className="h-4 w-4" /> },
  { title: "Bowl of Rice", value: <GiBowlOfRice className="h-4 w-4" /> },
  { title: "Apple", value: <FaApple className="h-4 w-4" /> },
  { title: "Carrot", value: <FaCarrot className="h-4 w-4" /> },
  { title: "Cheese", value: <FaCheese className="h-4 w-4" /> },
  { title: "Cookie Bite", value: <FaCookieBite className="h-4 w-4" /> },
  { title: "Martini", value: <FaGlassMartiniAlt className="h-4 w-4" /> },
  { title: "Lemon", value: <FaLemon className="h-4 w-4" /> },
  { title: "Cash Register", value: <FaCashRegister className="h-4 w-4" /> },
  { title: "Shopping Cart", value: <FaShoppingCart className="h-4 w-4" /> },
  { title: "Bread Slice", value: <FaBreadSlice className="h-4 w-4" /> },
  { title: "Sausage", value: <TbSausage className="h-4 w-4" /> },
  { title: "Bottle", value: <TbBottle className="h-4 w-4" /> },
  { title: "Shisha", value: <GiSmokingPipe className="h-4 w-4" /> },
  { title: "Drinks", value: <RiDrinksFill className="h-4 w-4" /> },
  { title: "Chef", value: <LuChefHat className="h-4 w-4" /> },
  { title: "Appetizer", value: <TbSalad className="h-4 w-4" /> },
  { title: "Chicken", value: <GiChickenOven className="h-4 w-4" /> },
  { title: "Juice", value: <GiManualJuicer className="h-4 w-4" /> },
  { title: "Kids Meal", value: <MdChildCare className="h-4 w-4" /> },
  { title: "Bottle 2", value: <FaBottleWater className="h-4 w-4" /> },
  { title: "Dish", value: <BiSolidDish className="h-4 w-4" /> },
  { title: "Energy", value: <SlEnergy className="h-4 w-4" /> },
  { title: "Cool Off", value: <GiCooler className="h-4 w-4" /> },
  { title: "Soft Drinks", value: <RiDrinks2Fill className="h-4 w-4" /> },
  { title: "Mixed Drinks", value: <FaWineBottle className="h-4 w-4" /> },
  { title: "Apple 2", value: <FaAppleAlt className="h-4 w-4" /> },
  { title: "Blender", value: <FaBlender className="h-4 w-4" /> },
  { title: "Cookie", value: <FaCookie className="h-4 w-4" /> },
  { title: "Drumstick Bite", value: <FaDrumstickBite className="h-4 w-4" /> },
  { title: "Pepper Hot", value: <FaPepperHot className="h-4 w-4" /> },
  { title: "Wine Glass", value: <FaWineGlassAlt className="h-4 w-4" /> },
  { title: "Martini Glass", value: <FaGlassMartiniAlt className="h-4 w-4" /> },
  { title: "Cocktail", value: <FaCocktail className="h-4 w-4" /> },

  { title: "Bacon", value: <GiBacon className="h-4 w-4" /> },
  { title: "Beer Mug", value: <GiBeerStein className="h-4 w-4" /> },
  { title: "Big Egg", value: <GiBigEgg className="h-4 w-4" /> },
  { title: "Vapor Bottle", value: <GiBottleVapors className="h-4 w-4" /> },
  { title: "Cabbage", value: <GiCabbage className="h-4 w-4" /> },
  { title: "Canned Fish", value: <GiCannedFish className="h-4 w-4" /> },
  { title: "Cheese Wedge", value: <GiCheeseWedge className="h-4 w-4" /> },
  { title: "Chopsticks", value: <GiChopsticks className="h-4 w-4" /> },
  { title: "Clams", value: <GiClaymoreExplosive className="h-4 w-4" /> },
  { title: "Coconut", value: <GiCoconuts className="h-4 w-4" /> },
  { title: "Chef Hat", value: <GiCook className="h-4 w-4" /> },
  { title: "Croissant", value: <GiCroissant className="h-4 w-4" /> },
  { title: "Cupcake", value: <GiCupcake className="h-4 w-4" /> },
  { title: "Egg", value: <GiEggPod className="h-4 w-4" /> },
  { title: "Flour Bag", value: <GiFlour className="h-4 w-4" /> },
  { title: "French Fries", value: <GiFrenchFries className="h-4 w-4" /> },
  { title: "Honey Jar", value: <GiHoneyJar className="h-4 w-4" /> },
  { title: "Hot Spices", value: <GiHotSpices className="h-4 w-4" /> },
  { title: "Milk Carton", value: <GiMilkCarton className="h-4 w-4" /> },
  { title: "Mushroom", value: <GiMushroom className="h-4 w-4" /> },
  { title: "Pineapple", value: <GiPineapple className="h-4 w-4" /> },
  { title: "Pizza Slice", value: <GiPizzaSlice className="h-4 w-4" /> },
  { title: "Potato", value: <GiPotato className="h-4 w-4" /> },
  { title: "Shrimp", value: <GiShrimp className="h-4 w-4" /> },
  { title: "Tomato", value: <GiTomato className="h-4 w-4" /> },

  { title: "Cake", value: <TbCake className="h-4 w-4" /> },
  { title: "Coffee Cup", value: <TbCoffee className="h-4 w-4" /> },
  { title: "Milk Bottle", value: <TbMilk className="h-4 w-4" /> },
  { title: "Ice Cream Cone", value: <TbIceCream2 className="h-4 w-4" /> },
  { title: "Chopsticks", value: <TbBowlChopsticks className="h-4 w-4" /> },
  { title: "Apple 3", value: <TbApple className="h-4 w-4" /> },
  { title: "Cup", value: <TbCup className="h-4 w-4" /> },

  { title: "Food Bank", value: <MdFoodBank className="h-4 w-4" /> },
  { title: "Fast Food", value: <MdFastfood className="h-4 w-4" /> },
  { title: "Ice Cream 2", value: <MdIcecream className="h-4 w-4" /> },
  { title: "Pizza Slice", value: <MdLocalPizza className="h-4 w-4" /> },
  { title: "Wine Bar", value: <MdOutlineWineBar className="h-4 w-4" /> },
  { title: "Ramen", value: <MdRamenDining className="h-4 w-4" /> },
  { title: "Set Meal", value: <MdOutlineSetMeal className="h-4 w-4" /> },
  { title: "GiSandwich", value: <GiSandwich className="h-4 w-4" /> },
  { title: "burger", value: <PiHamburgerFill className="h-4 w-4" /> },
];

export const getIconByTitle = (title: string) => {
  return iconOptions.find((icon) => icon.title === title) || null;
};
